config/routes.rb
PracticeInterview::Application.routes.draw do
  resources :interviews

  devise_for :users

  authenticated do
    root to: "home#show", as: :authenticated_root
  end

  root to: "home#index"
end

app/models/interview.rb
class Interview < ActiveRecord::Base
  belongs_to :user

  validates :job_url, presence: true
  validates :resume_url, presence: true, format: URI::regexp(%w(http https))
  validates :time, presence: true
end

app/models/mixpanel_events.rb
module MixpanelEvents
  HomeController.before_filter -> { track_visited_landing_page }, only: :index
  Devise::RegistrationsController.before_filter -> { track_clicked_cta }, only: :new
  Devise::RegistrationsController.before_filter -> { track_signed_up }, only: :create
  InterviewsController.before_filter -> { track_created_interview }, only: :create

  private
    def track_visited_landing_page
      mixpanel.track 'visited_landing_page', source: params[:source] || 'direct'
    end

    def track_clicked_cta
      mixpanel.track 'clicked_cta', position: params[:position]
    end

    def track_signed_up
      mixpanel.track 'signed_up'
    end

    def track_created_interview
      mixpanel.track 'created_interview'
    end 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :interviews

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  def first_name
    name.split(' ').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  before_filter :identify_mixpanel_user

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    end

    def mixpanel
      @mixpanel ||= Mixpanel::Tracker.new ENV["MIXPANEL_TOKEN"], env: request.env, persist: true
    end

  private
    def identify_mixpanel_user
      mixpanel.set current_user.id if current_user
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, only: :show
  layout 'public', only: :index

  def index
  end

  def show
    @interviews = current_user.interviews
    redirect_to new_interview_path if @interviews.empty?
  end
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  respond_to :html

  def new
    @interview = current_user.interviews.build
  end

  def create
    @interview = current_user.interviews.create interview_params

    respond_with @interview
  end

  def show
    @interview = current_user.interviews.find params[:id]
  end

  private
    def interview_params
      params.require(:interview).permit \
        :job_url, :resume_url, :description, :time
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Stolen from devise_error_messages!
  def error_messages_for(model)
    return "" if model.errors.empty?

    messages = model.errors.inject({}) do |memo, (prop, issue)|
      memo[prop] ||= issue
      memo
    end.map do |prop, issue|
      content_tag(:li, model.errors.full_message(prop, issue))
    end

    sentence = I18n.t("errors.messages.unsaved",
                      :count => messages.count,
                      :model => model.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages.join}</ul>
    </div>
    HTML

    html.html_safe
  end

end

app/views/home/index.slim
.container
  .jumbotron
    h1 Get hired faster.
    p Practice interviews with working professionals in your field, from anywhere.
    = link_to new_user_registration_path(position: "primary"), class: "btn btn-primary btn-lg" do
      | Try it free! &nbsp;
      i.icon-circle-arrow-right
    span.hint
      | (with just a name and email)

.content
  .container
    ul.row
      li.detail.panel.panel-info
        .panel-heading
          i.icon-facetime-video
        h4 Phone or video
        p
          | We'll set up a phone call or a video chat &mdash; whichever 
          | is most comfortable and useful to you. And we'll send you 
          | a recording when we're done (if you want).

      li.detail.panel.panel-info
        .panel-heading
          i.icon-refresh
        h4 Instant feedback
        p
          | You'll chat with someone who works and interviews in your field. 
          | Get insider information on what interviewers <em>really</em> want to know 
          | when they ask certain questions.

      li.detail.panel.panel-info
        .panel-heading
          i.icon-check
        h4 Expert advice
        p
          | If you have specific questions about an upcoming job interview, 
          | we'll help you out. Be prepared and stick the interview.

    .row.cta
      .well
        h3 Now interviewing: designers, developers, and more.
        = link_to "Sign up now", new_user_registration_path(position: "secondary"), class: "btn btn-primary btn-lg", position: "secondary"

app/views/home/show.slim
h2 Interviews

- if @interviews.any?
  table.table.table-striped
    - @interviews.each do |interview|
      tr
        td= link_to "Interview for #{interview.job_url} @ #{interview.time}", interview_path(interview)

= link_to "New Interview", new_interview_path, class: "btn btn-primary", "data-track" => "clicked_new_interview"

app/views/interviews/new.slim
- if current_user.interviews.length == 1 # there's only the one for this form
  .welcome.panel
    h3 Welcome to #{t :brand}!
    p.text-muted To get started, we just need to know a few things about the jobs you're looking at.
    p.text-muted After that, we'll be in touch to schedule your <em>free</em> practice interview.


.row
  .col-lg-6.col-lg-offset-3
    h2 New Interview
    = form_for @interview do |f|
      = error_messages_for @interview
      .form-group
        = f.label :job_url, "What position are you applying for?"
        span.text-muted
          |  (Job URL or title)
        = f.text_field :job_url, autofocus: true, required: true, class: "form-control"
      .form-group
        = f.label :resume_url, "What's your LinkedIn profile URL?"
        span.text-muted
          |  (or other resume URL)
        = f.text_field :resume_url, required: true, class: "form-control"
      .form-group
        = f.label :description, "Tell us more about the job"
        span.text-muted
          |  (optional)
        = f.text_area :description, rows: 8, class: "form-control"
      .form-group
        = f.label :time, "When do you want to interview?"
        span.text-muted
          |  (ex: tomorrow afternoon, Thursday at 2)
        = f.text_field :time, required: true, class: "form-control"
      .form-group
        = f.submit "Submit", class: "btn btn-primary", "data-track" => "created_interview"

app/views/interviews/show.slim
.welcome.panel
  h3.text-center We've received your interview request!
  p.text-muted.text-center We'll be in touch soon to confirm your interview schedule. 
  ol.steps.row
    li.col-lg-2.col-lg-offset-2.selected 1. Tell Us About Your Job
    li.col-lg-1.spacer.selected
    li.col-lg-2.selected 2. Schedule an Interview
    li.col-lg-1.spacer
    li.col-lg-2 3. Get Great Feedback!

  .row
    .well.col-lg-4.col-lg-offset-4
      dl.dl-horizontal
        dt Job URL
        dd= @interview.job_url

        dt Resume URL
        dd= @interview.resume_url

        dt Description
        dd= @interview.description

        dt Time
        dd= @interview.time

app/views/layouts/application.slim
doctype html
html
  head
    title= t :brand
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags

  body class="#{params[:controller].parameterize.gsub('-', ' ')}"
    #wrap
      .navbar
        .container
          = link_to root_path, class: 'navbar-brand' do
            i.icon-compass
            = t(:brand)
          .nav-collapse.collapse
            ul.nav.navbar-nav
              - if current_user
                li= link_to "Sign Out", destroy_user_session_path, method: :delete
              - else
                li= link_to "Sign Up", new_user_registration_path
                li= link_to "Sign In", new_user_session_path

      .container
        - if notice
          p.alert.alert-info
            button type="button" class="close" data-dismiss="alert" &times;
            = notice
        - if alert
          p.alert.alert-danger= alert

        = yield

      #push

    footer#footer
      .container
        p.text-muted.credit
          | (c) 2013 Refoundry.co

app/views/layouts/public.slim
doctype html
html
  head
    title= t :brand
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="title" content="SimHire | Get hired faster with practice interviews + expert feedback."
    meta name="description" content="Practice interviews and expert feedback from working professionals in your field. Phone or online. Schedule an interview today!"
    meta property="og:url" content="http://www.simhire.com"
    meta property="og:title" content="SimHire | Get hired faster with practice interviews + expert feedback."
    meta property="og:description" content="Practice interviews and expert feedback from working professionals in your field. Phone or online. Schedule an interview today!"
    meta property="og:image" content="http://simhire.com/assets/bg-edb3563f0715dd4caadf0b1a3f878a82.jpg"
    = csrf_meta_tags

  body class="public #{params[:controller]}"
    #wrap
      .navbar
        .container
          = link_to root_path, class: 'navbar-brand' do
            i.icon-compass
            = t(:brand)
          .nav-collapse.collapse
            ul.nav.navbar-nav
              - if current_user
                li= link_to "Sign Out", destroy_user_session_path, method: :delete
              - else
                li= link_to "Sign Up", new_user_registration_path(position: 'header')
                li= link_to "Sign In", new_user_session_path

      = yield

      #push

    footer#footer
      .container
        p.text-muted.credit
          | &copy; 2013 #{link_to 'refoundry.co', 'http://refoundry.co'}
    - if Rails.env.production?
      javascript:
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-43197815-2', 'simhire.com');
        ga('send', 'pageview');